# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python"
  amd64: "ghcr.io/home-assistant/amd64-base-python"
  armhf: "ghcr.io/home-assistant/armhf-base-python"
  armv7: "ghcr.io/home-assistant/armv7-base-python"
  i386: "ghcr.io/home-assistant/i386-base-python"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: hacomfoairmqtt"
  org.opencontainers.image.description: "Add-on for hacomfoairmqtt and serial over IP"
  org.opencontainers.image.source: "https://github.com/DesertFox8/hacomfoairmqtt"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"